FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    clickhouse-driver

COPY requirements.txt .
RUN if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

CMD ["tail", "-f", "/dev/null"]