version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # Native интерфейс
      - "9009:9009"  # Для межсерверной репликации (опционально)
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_config:/etc/clickhouse-server
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password123}
      CLICKHOUSE_DB: test_db
    networks:
      - clickhouse-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./scripts:/app:rw
    depends_on:
      - clickhouse  # Просто ожидание запуска контейнера
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "9000"
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password123}
    working_dir: /app
    networks:
      - clickhouse-network

volumes:
  clickhouse_data:
  clickhouse_config:

networks:
  clickhouse-network: